trigger:
- master
- rel/*

pr:
- master
- rel/*

pool:
  vmImage: 'windows-2019'

variables: 
  BuildConfiguration: Release

steps:

- task: NuGetToolInstaller@0
  displayName: Use NuGet 5.0.0
  inputs:
    versionSpec: 5.0.0

- task: DotNetCoreInstaller@0
  inputs:
    packageType: 'sdk'
    version: '3.0.100-preview5-011568'
  displayName: Install Dot Net Core SDK 3.0

- task: DotNetCoreCLI@2
  inputs:
    command: custom
    custom: tool
    arguments: install --tool-path . nbgv
  displayName: Install NBGV tool

- script: nbgv cloud
  displayName: Set Version

- powershell: .\build\Install-WindowsSdkISO.ps1 18362
  displayName: Insider SDK

- task: BatchScript@1
  inputs:
    filename: "C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Enterprise\\Common7\\Tools\\VsDevCmd.bat"
    arguments: -no_logo
    modifyEnvironment: true
  displayName: Setup Environment Variables

- task: NuGetCommand@2
  displayName: NuGet restore Native project x64
  inputs:
    command: restore
    platform: x64
    configuration: Release
    restoreSolution: Microsoft.Toolkit.Win32.UI.XamlApplication\packages.config
    restoreDirectory: ../packages/
    verbosityRestore: Detailed # Options: quiet, normal, detaile

- task: NuGetCommand@2
  displayName: NuGet restore Native project x86
  inputs:
    command: restore
    platform: x86
    configuration: Release
    restoreSolution: Microsoft.Toolkit.Win32.UI.XamlApplication\packages.config
    restoreDirectory: ../packages/
    verbosityRestore: Detailed # Options: quiet, normal, detaile

#- powershell: .\build\build.ps1 -target=Package
#  displayName: Build 

- task: NuGetCommand@2
  displayName: NuGet restore x64
  inputs:
    command: restore
    platform: x64
    configuration: Release
    restoreSolution: Microsoft.Toolkit.Win32.sln
    restoreDirectory: packages/
    verbosityRestore: Detailed # Options: quiet, normal, detaile

- task: NuGetCommand@2
  displayName: NuGet restore x86
  inputs:
    command: restore
    platform: x86
    configuration: Release
    restoreSolution: Microsoft.Toolkit.Win32.sln
    restoreDirectory: packages/
    verbosityRestore: Detailed # Options: quiet, normal, detaile

- task: MSBuild@1
  displayName: Build x64 Restore
  inputs:
    solution: Microsoft.Toolkit.Win32.sln 
    platform: x64
    configuration: Release
    msbuildArguments: /target:Restore
    restoreNugetPackages: false # Optional

- task: MSBuild@1
  displayName: Build x64
  inputs:
    solution: Microsoft.Toolkit.Win32.sln 
    platform: x64
    configuration: Release
    msbuildArguments: /target:Build
    restoreNugetPackages: false # Optional

- task: MSBuild@1
  displayName: Build x86 Restore
  inputs:
    solution: Microsoft.Toolkit.Win32.sln 
    platform: x86
    configuration: Release
    msbuildArguments: /target:Restore
    restoreNugetPackages: false # Optional

- task: MSBuild@1
  displayName: Build x86
  inputs:
    solution: Microsoft.Toolkit.Win32.sln 
    platform: x86
    configuration: Release
    msbuildArguments: /target:Build
    restoreNugetPackages: false # Optional

- task: MSBuild@1
  displayName: Build Pack
  inputs:
    solution: Microsoft.Toolkit.Win32.sln 
    platform: x86
    configuration: Release
    msbuildArguments: /target:Pack
    restoreNugetPackages: false # Optional

- task: PowerShell@2
  displayName: Authenticode Sign Packages
  inputs:
    filePath: build/Sign-Package.ps1
  env:
    SignClientUser: $(SignClientUser)
    SignClientSecret: $(SignClientSecret)
    ArtifactDirectory: bin\nupkg
  condition: and(succeeded(), not(eq(variables['build.reason'], 'PullRequest')), not(eq(variables['SignClientSecret'], '')), not(eq(variables['SignClientUser'], '')))

- task: PublishBuildArtifacts@1
  displayName: Publish Package Artifacts
  inputs:
    pathToPublish: .\bin\nupkg
    artifactType: container
    artifactName: Packages
